### ISSUE TITLE
Some image cannot be cropped when selecting from "My Photo Stream" album

### ISSUE THREAD

**Issue by KieuQ** [guoyingtao/Mantis#12]
When supplying an image directly from UIImagePickerController and from "My Photo Stream" album, some photos fails to crop
debugger logs: `[Unknown process name] CGBitmapContextInfoCreate: CGColorSpace does't support output`

**Comment by guoyingtao** [comment]
Would you mind sharing one of those photos which failed to crop with me? Thank you!

**Comment by guoyingtao** [comment]
Would you mind sharing some codes of getting images from your image gallery? Sometimes the image gallery needs to download image data from iCloud then return the real image. I am not sure if it is the reason for the problem. I just tested on my device running iOS 13. I got an image from my image gallery and successfully cropped it with Mantis.

**Comment by KieuQ** [comment]
Sorry about the late response

The device I'm using is on iOS 13 

I just present the `UIImagePickerController` like this
```
let controller: UIImagePickerController = UIImagePickerController()
controller.sourceType = .photoLibrary
controller.delegate = delegate
controller.modalPresentationStyle = .overCurrentContext

present(controller, animated: true)
```
and the delegate function
```
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
	picker.dismiss(animated: true)

	if let image: UIImage = info[.originalImage] as? UIImage {
		let viewController: CropViewController = Mantis.cropViewController(image: image)
		viewController.modalPresentationStyle = .overCurrentContext
		viewController.delegate = self
		
		present(viewController, animated: true)
	} else {
		// error alert
	}
}
```
also here's one of the images in question although I don't think it's an issue with the image since I can crop it when I pick it through "All Photos"
![0BA17415-D0D1-4E47-AA1B-1066D84E2981 (1)](https://user-images.githubusercontent.com/20398239/69300732-05f34480-0c4f-11ea-8564-bdf34e66d9d9.JPG)

**Comment by guoyingtao** [comment]
Thanks for providing the example photo!
It is because the color space of this photo is "Apple Wide Color Sharing Profile", which can not be used as a destination color space.
I will fixed this problem in the next release.

**Comment by guoyingtao** [comment]
@KieuQ I just released Mantis 0.40. You can try this version to see if it solves your problem or not.

**Comment by KieuQ** [comment]
Got it, I'll confirm if it's fixed on my side

**Comment by KieuQ** [comment]
A tester of mine still cannot crop an image, I need to collect some logs and come back here
heres a recording from him
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20398239/69321718-8aa98700-0c7e-11ea-88e5-bd9ca45a9e61.gif)

**Comment by guoyingtao** [comment]
@KieuQ Thanks for the test! Did it still show `[Unknown process name] CGBitmapContextInfoCreate: CGColorSpace does't support output` again? 
Also, did you test the image you shared with me? If it worked for that image, but didn't work for the new image like this oil painting, would you mind sharing this image to me too?

**Comment by KieuQ** [comment]
@guoyingtao I don't know if it still logs `[Unknown process name] CGBitmapContextInfoCreate: CGColorSpace does't support output` at the moment, I need to wait for the tester to come to office with the device his using since he's testing remotely and the other devices I have right now isn't able to replicate this issue.
Also the image he is trying to crop is actually a screenshot, might be the same issue as  #13

**Comment by yingtao-futurewonder** [comment]
@KieuQ Thanks for the information.  I reproduced this bug by using the first photo you provided and saw the same error log: `[Unknown process name] CGBitmapContextInfoCreate: CGColorSpace doesn't support output`. Then I fixed it by providing a default colorspace when finding the photo's colorspace does not support outputting.

Can you help to check if you can find the following code after updating  Mantis to 0.40 in CGImageExtensions.swift? Thank you.

```
        // If the color space does not allow output, default to the RGB color space
        if (!colorSpaceRef.supportsOutput) {
            colorSpaceRef = CGColorSpaceCreateDeviceRGB();
        }
```

**Comment by KieuQ** [comment]
@yingtao-futurewonder Yes, here's the screenshot 
![Screen Shot 2019-11-22 at 11 59 54](https://user-images.githubusercontent.com/20398239/69397088-b6307e00-0d1f-11ea-94b2-a47909b57887.png)

**Comment by guoyingtao** [comment]
@KieuQ Thanks for the checking. It is the newest version. Would you mind sharing that oil painting photo with me too?

**Comment by KieuQ** [comment]
@guoyingtao Here's what my tester was trying to crop, I can crop it successfully with iPad Air 2 on ios13 but while he can't crop screenshots with his iPad Pro (9.7-inch) also on iOS 13
![IMG_3717](https://user-images.githubusercontent.com/20398239/69398575-bcc1f400-0d25-11ea-92ef-8094b554c4a5.JPG)

**Comment by KieuQ** [comment]
@guoyingtao Hi, this is the log for when cropping screenshots with my testers iPad Pro
```
[Unknown process name] CGBitmapContextCreate: unsupported parameter combination: set CGBITMAP_CONTEXT_LOG_ERRORS environmental variable to see the details
```

**Comment by yingtao-futurewonder** [comment]
@KieuQ I don't have an iPad pro. I tested this photo on the iPad pro simulator and it worked. If you can provide some log information later when you can connect your iPad pro to XCode, that would be helpful!

**Comment by KieuQ** [comment]
Also the issue where I cannot crop some images from 'My Photo Stream' is now fixed, so the issue I'm now encountering is the same as #13

**Comment by yingtao-futurewonder** [comment]
@KieuQ Thanks for the information. I don't have an iPad pro. So I may need to find one to reproduce this bug... I tested on an iPad pro simulator it worked though. Can you also help to check if it also happens on other iOS devices?

**Comment by guoyingtao** [comment]
Thanks for the information. I don't have an iPad pro. So I may need to find one to reproduce this bug... I tested on an iPad pro simulator it worked though. Can you also help to check if it also happens on other iOS devices?

**Comment by KieuQ** [comment]
It doesn't happen to the other devices I have, only the iPad Pro (9.7-inch)

**Comment by guoyingtao** [comment]
@KieuQ Do you have that iPad pro at hand? Can you change` bitmapInfo: self.bitmapInfo.rawValue` to` bitmapInfo: CGImageAlphaInfo.premultipliedFirst.rawValue ` in CGImageExtensions.swift in your pod files to see if it works. Thanks!

**Comment by KieuQ** [comment]
@guoyingtao Hi, setting it to `CGImageAlphaInfo.premultipliedFirst.rawValue` doesn't fix it but `CGImageAlphaInfo.premultipliedLast.rawValue` does fix it

**Comment by guoyingtao** [comment]
@KieuQ Thanks for the information. It is really helpful! I will fix it in the next release.

**Comment by KieuQ** [comment]
@guoyingtao Thank you too

**Comment by guoyingtao** [comment]
@KieuQ I just released Mantis 0.41. Please check if it solved the bug. Thank you!

**Comment by KieuQ** [comment]
@guoyingtao issue is now fixed, thanks

**Comment by guoyingtao** [comment]
@KieuQ No problem. Thanks for the feedback!
