### ISSUE TITLE
When I take screenshot and upload image from gallery , I can't crop.

### ISSUE THREAD

**Issue by nickstefanidis** [guoyingtao/Mantis#13]
As I mention in the title when I take a screenshot I can't crop the image. The "Done" button does nothing and I can only use cancel. 
Thank you.

**Comment by guoyingtao** [comment]
Thanks for your feedback! Can you also tell me the iOS version of your device? Thank you!

**Comment by guoyingtao** [comment]
Would you mind sharing some codes of getting images from your image gallery? Sometimes the image gallery needs to download image data from iCloud then return the real image. I am not sure if it is the reason for the problem. I just tested on my device running iOS 13. I got an image from my image gallery and successfully cropped it with Mantis.

**Comment by guoyingtao** [comment]
@NickStef92 I just released Mantis 0.40. You can try this version to see if it solves your problem or not.

**Comment by NickStef92** [comment]
Hello and sorry for the late response. So I updated the library in version 0.40 but when I take a screenshot and the. try to crop it, the. Done button do nothing. IOS 13.1.

`func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
    
        if let selectedImage = info[.originalImage] as? UIImage{
            dismiss(animated: true, completion: {
                
                let cropViewController = Mantis.cropViewController(image: selectedImage)
                if #available(iOS 13, *) {
                    cropViewController.modalPresentationStyle = .fullScreen
                }
                cropViewController.delegate = self
                self.present(cropViewController, animated: true)
            })
        }
        
    }`

This is the code.

**Comment by guoyingtao** [comment]
@NickStef92 Thanks for the information! I reproduced this bug. I will fix it in the next release.

**Comment by NickStef92** [comment]
Thank you!

**Comment by guoyingtao** [comment]
@NickStef92 I just released Mantis 0.41. Please check if it solved the bug. Thank you!

**Comment by NickStef92** [comment]
Hello and thank you. Unfortunately this didn't solve the bug. I get the same error.

**Comment by guoyingtao** [comment]
@NickStef92 Thanks for the feedback! 

Can you help to check if you can find the following code after updating Mantis to 0.41 in CGImageExtensions.swift in your pod files? Thank you.

Also, would you mind sharing your screenshot with me. Thank you!

```
        var context = CGContext(data: nil,
                                width: Int(outputSize.width),
                                height: Int(outputSize.height),
                                bitsPerComponent: self.bitsPerComponent,
                                bytesPerRow: bitmapBytesPerRow,
                                space: colorSpaceRef,
                                bitmapInfo: self.bitmapInfo.rawValue)

        if context == nil {
            context = CGContext(data: nil,
            width: Int(outputSize.width),
            height: Int(outputSize.height),
            bitsPerComponent: self.bitsPerComponent,
            bytesPerRow: bitmapBytesPerRow,
            space: colorSpaceRef,
            bitmapInfo:CGImageAlphaInfo.premultipliedLast.rawValue)
        }

        if context == nil {
            context = CGContext(data: nil,
            width: Int(outputSize.width),
            height: Int(outputSize.height),
            bitsPerComponent: self.bitsPerComponent,
            bytesPerRow: bitmapBytesPerRow,
            space: colorSpaceRef,
            bitmapInfo:CGImageAlphaInfo.premultipliedFirst.rawValue)
        }

```

**Comment by NickStef92** [comment]
@guoyingtao Yes I found it. There is no specific image for the issue.This happens every time I pass an image that I took with screen screenshot.

**Comment by guoyingtao** [comment]
@NickStef92 I did reproduced this bug by passing screenshot image to corp. After adding the code I mentioned above, the bug is fixed on my device. So if you can provide some screenshot from your device, it may help me locate the bug. Thank you very much!
Also, would you mind providing some information of your device like iOS version, etc.

**Comment by premcodes1** [comment]
@guoyingtao i am using pod version0.41...even i had the issue with the done button....it doesnt work sometimes..seems like done button will work only if we click on "DO" part of the "Done"..it will happens only when we take screenshot images , that images are blocking the gestures of done button ... pls solve

**Comment by guoyingtao** [comment]
@premcodes1 Thanks for the feedback! The current Mantis version is 0.43. Would you mind to try this version to see if the problem is solved?

**Comment by premcodes1** [comment]
> @premcodes1 Thanks for the feedback! The current Mantis version is 0.43. Would you mind to try this version to see if the problem is solved?

Solved this problem temporarily... this problem exists only if we use ipad in landscapeleft..
so..in "cropViewController.swift" i changed the stackView for order for landscapeleft in line number 301

**Comment by guoyingtao** [comment]
@avijeetpandey Thanks for the feedback.
Can you post the image you are using here then I can have a test too? Thanks!

**Comment by avijeetpandey-probo** [comment]
@guoyingtao I am using image captured from camera, is that okay ?

**Comment by avijeetpandey-probo** [comment]
@guoyingtao it is happening on all the images captured using AVFoundation framework , with raw output.

**Comment by guoyingtao** [comment]
@avijeetpandey Can you post one picture captured by AVFoundation on your device here?

**Comment by Dongs77** [comment]
![B963241E-8B9D-4AAE-9269-FC2A837B3FD7_1_105_c](https://github.com/guoyingtao/Mantis/assets/38485643/d67280e4-c867-49c2-8847-229087960409)
