### ISSUE TITLE
Allow users to add a customized toolbar

### ISSUE THREAD

**Issue by guoyingtao** [guoyingtao/Mantis#33]

**Comment by guoyingtao** [comment]
Mantis 1.1.0 is released with a CustomizedCropToolbar conform to CropToolbarProtocol in the example project.

**Comment by mschonvogel** [comment]
@guoyingtao Looks good, thank you so much! The only thing I noticed is that`handleCropViewDidBecomeUnResettable()` is not getting called after having called `cropToolbarDelegate?.didSelectedReset()`.

(And all these didSelect**ed**... functions should probably be called `didSelect…`.

**Comment by guoyingtao** [comment]
@mschonvogel You are right. I will fix them in the next release.

**Comment by guoyingtao** [comment]
@mschonvogel I released Mantis 1.1.1. I add delegate?.cropViewDidBecomeUnResettable(self) to the reset() function in CropView.swift. That way every time the status is reset, the handleCropViewDidBecomeUnResettable() of CropToolbar will be called.

**Comment by mschonvogel** [comment]
Ok, `thathandleCropViewDidBecomeUnResettable` is getting called now.

function naming is still wrong: didSelect**e** remove the `e` 😜

**Comment by guoyingtao** [comment]
You are right 😂 Will fix it.

**Comment by guoyingtao** [comment]
I fixed this issue in Mantis 1.2.0.

**Comment by mschonvogel** [comment]
Awesome
